In [1]:
class test:
    def test_meth(self):
        return "This is my first class"

In [2]:
class child_test(test):
    pass

In [3]:
child_test_obj= child_test()

In [4]:
child_test_obj.test_meth()

'This is my first class'

In [5]:
import numpy as np

In [6]:
my_arr=np.arange(100000)

In [7]:
my_list=list(range(1000000))

In [8]:
data = np.random.randn(2,3)

In [9]:
data

array([[-0.12928045, -0.18514894,  1.02566885],
       [ 0.87381582, -0.17010346, -1.21676507]])

In [10]:
data * 10

array([[ -1.29280451,  -1.85148936,  10.25668854],
       [  8.73815822,  -1.70103462, -12.16765071]])

In [11]:
data + data

array([[-0.2585609 , -0.37029787,  2.05133771],
       [ 1.74763164, -0.34020692, -2.43353014]])

In [12]:
data -data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

In [15]:
data1=[6,3,55,22.11,0,1]

In [16]:
arr1=np.array(data1)

In [17]:
arr1

array([ 6.  ,  3.  , 55.  , 22.11,  0.  ,  1.  ])

In [18]:
data2=[[1,2,3,4],[5,6,7,8]]

In [19]:
arr2=np.array(data2)

In [20]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
arr2.ndim

2

In [22]:
arr2.shape

(2, 4)

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr2.dtype

dtype('int32')

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.empty((2,3,2))

array([[[9.61247826e-312, 2.56914136e-322],
        [0.00000000e+000, 0.00000000e+000],
        [2.67020407e-306, 1.16095484e-028]],

       [[3.65093134e+233, 8.97600969e-096],
        [1.46899930e+179, 9.08367237e+223],
        [1.16466228e-028, 5.56269503e-309]]])

In [28]:
np.arange(14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [29]:
arr1=np.array([1,2,3],dtype=np.float64)

In [30]:
arr1

array([1., 2., 3.])

In [31]:
arr2=np.array([1,2,3],dtype=np.int32)

In [32]:
arr1.dtype

dtype('float64')

In [33]:
arr2.dtype

dtype('int32')

In [34]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
arr2d[2]

array([7, 8, 9])

In [36]:
arr2d[0][2]

3

In [37]:
arr2d[0,2]

3

In [38]:
arr3d=([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [39]:
arr3d

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

In [40]:
arr3d[0]

[[1, 2, 3], [4, 5, 6]]

In [41]:
arr2d[:2,2]

array([3, 6])

In [42]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [43]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [44]:
arr= np.empty((8,4))

In [46]:
for i in range(8):
    arr[i]=i

In [47]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [48]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [49]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [54]:
arr=np.arange(32).reshape(8,4)

In [45]:
arr

array([[9.61245960e-312, 1.02765654e-321, 0.00000000e+000,
        0.00000000e+000],
       [1.50661701e-312, 5.02034658e+175, 1.66946118e-047,
        6.59447862e-066],
       [2.57394651e-056, 9.14627176e-071, 6.44386391e-067,
        8.06989239e-144],
       [3.59751658e+252, 3.96046095e+246, 1.04918621e-153,
        7.69165785e+218],
       [5.04621343e+180, 1.04917822e-153, 9.08366793e+223,
        1.66946118e-047],
       [6.59447862e-066, 2.57394651e-056, 9.14627176e-071,
        1.04917753e-153],
       [1.94918966e-153, 3.93230450e-062, 1.48330714e-071,
        3.31032788e-033],
       [2.59027896e-144, 7.79952704e-143, 5.81186265e+294,
        1.14033976e-308]])

In [46]:
arr[[1,5,7,2],[0,3,1,2]]

array([1.50661701e-312, 1.04917753e-153, 7.79952704e-143, 6.44386391e-067])