In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]


In [3]:
arr =np.array(l)

In [4]:
arr


array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a=[2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
b= np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
type(b)


numpy.matrix

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [14]:
# swallow copy 
c=a

In [15]:
c

[2, 3, 4]

In [16]:
c[0]=100

In [17]:
c

[100, 3, 4]

In [18]:
a

[100, 3, 4]

In [19]:
# deep copy 
d= np.copy(a)

In [20]:
d

array([100,   3,   4])

In [21]:
a[1]=400

In [22]:
a

[100, 400, 4]

In [24]:
c

[100, 400, 4]

In [25]:
d

array([100,   3,   4])

In [28]:
np.fromfunction(lambda i,j:i==j ,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [29]:
np.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [39]:
iterable=(i*i for i in range(5))

In [40]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [46]:
np.fromstring('5,7',sep=', ')

array([5., 7.])

In [47]:
np.fromstring('4545 343 5343 43434 ',sep=" ")

array([ 4545.,   343.,  5343., 43434.])

In [48]:
#Numpy=data Types

In [49]:
l1=[1,2,3,4,56]

In [50]:
arr=np.array(l1)

In [51]:
arr

array([ 1,  2,  3,  4, 56])

In [52]:
arr.ndim

1

In [53]:
arr2=np.array([[1,2,3,4],[4,4,5,6]])

In [54]:
arr2

array([[1, 2, 3, 4],
       [4, 4, 5, 6]])

In [55]:
arr2.ndim

2

In [56]:
arr.size

5

In [57]:
arr2.size


8

In [58]:
arr.shape

(5,)

In [59]:
arr2.shape

(2, 4)

In [60]:
arr.dtype

dtype('int32')

In [61]:
arr2.dtype

dtype('int32')

In [63]:
arr3=np.array([(1,4,33.4,6),(5,64,3,2)])

In [64]:
arr3

array([[ 1. ,  4. , 33.4,  6. ],
       [ 5. , 64. ,  3. ,  2. ]])

In [65]:
arr3.dtype

dtype('float64')

In [68]:
list(range(5))

[0, 1, 2, 3, 4]

In [70]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [80]:
list(np.arange(2.3,9.0,.01))

[2.3,
 2.3099999999999996,
 2.3199999999999994,
 2.329999999999999,
 2.339999999999999,
 2.3499999999999988,
 2.3599999999999985,
 2.3699999999999983,
 2.379999999999998,
 2.389999999999998,
 2.3999999999999977,
 2.4099999999999975,
 2.4199999999999973,
 2.429999999999997,
 2.439999999999997,
 2.4499999999999966,
 2.4599999999999964,
 2.469999999999996,
 2.479999999999996,
 2.4899999999999958,
 2.4999999999999956,
 2.5099999999999953,
 2.519999999999995,
 2.529999999999995,
 2.5399999999999947,
 2.5499999999999945,
 2.5599999999999943,
 2.569999999999994,
 2.579999999999994,
 2.5899999999999936,
 2.5999999999999934,
 2.609999999999993,
 2.619999999999993,
 2.629999999999993,
 2.6399999999999926,
 2.6499999999999924,
 2.659999999999992,
 2.669999999999992,
 2.6799999999999917,
 2.6899999999999915,
 2.6999999999999913,
 2.709999999999991,
 2.719999999999991,
 2.7299999999999907,
 2.7399999999999904,
 2.7499999999999902,
 2.75999999999999,
 2.76999999999999,
 2.7799999999999896,
 2.789999

In [82]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [85]:
np.ones((8,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [87]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [90]:
arr5=np.ones((2,3,2))

In [91]:
arr5

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [92]:
arr5*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [96]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [97]:
np.eye(16)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [99]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [100]:
np.logspace(2,5,200)

array([   100.        ,    103.53218433,    107.18913192,    110.97524964,
          114.89510002,    118.95340674,    123.15506033,    127.50512407,
          132.00884008,    136.67163565,    141.49912974,    146.49713983,
          151.67168885,    157.02901247,    162.57556664,    168.31803533,
          174.2633386 ,    180.41864094,    186.7913599 ,    193.38917505,
          200.22003718,    207.29217796,    214.61411979,    222.19468609,
          230.04301198,    238.1685552 ,    246.58110758,    255.29080682,
          264.3081487 ,    273.64399971,    283.30961018,    293.31662784,
          303.6771118 ,    314.40354716,    325.50885998,    337.00643293,
          348.91012134,    361.23426997,    373.99373025,    387.20387818,
          400.88063289,    415.04047579,    429.70047043,    444.87828311,
          460.59220411,    476.86116977,    493.70478528,    511.14334834,
          529.1978736 ,    547.89011796,    567.24260685,    587.27866132,
          608.02242616,  

In [102]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [106]:
arr6=np.random.randn(3,4)

In [107]:
import pandas as pd

In [108]:
pd.DataFrame(arr6)

0         1         2         3
0  0.359834 -0.613827 -1.127225  0.292258
1  0.864378  1.129332  1.482280  0.677651
2 -0.337016  0.936707  0.214799  0.484269

In [109]:
np.random.rand(3,7)

array([[0.14869616, 0.15210125, 0.31839576, 0.94082133, 0.13418727,
        0.10530704, 0.79074017],
       [0.21004304, 0.64498346, 0.14344418, 0.78147815, 0.64022769,
        0.55982352, 0.15017312],
       [0.3188358 , 0.52525247, 0.79734593, 0.96451646, 0.94634281,
        0.07281107, 0.42889978]])

In [110]:
pd.DataFrame(np.random.rand(4,5))

0         1         2         3         4
0  0.179289  0.140957  0.430835  0.245339  0.649212
1  0.018104  0.629063  0.099326  0.458775  0.673440
2  0.946026  0.137488  0.053704  0.326373  0.058505
3  0.446799  0.178261  0.453272  0.295293  0.846561

In [111]:
np.random.randint(2,220,(5,5))

array([[166, 154,  44,  23,   9],
       [ 67, 150, 119,  44, 201],
       [ 27, 155,  69, 215, 128],
       [ 41, 197, 137,  60,  49],
       [120, 139,  33,  76, 146]])

In [112]:
pd.DataFrame(np.random.randint(2,220,(300,400))).to_csv("test.csv")

In [113]:
arr7=np.random.rand(3,4)

In [114]:
arr7

array([[0.97643132, 0.37129977, 0.48582942, 0.19083978],
       [0.70624454, 0.69207355, 0.01576252, 0.00551988],
       [0.0816228 , 0.89158668, 0.72745765, 0.29228988]])

In [117]:
arr8=arr7.reshape(6,-1)

In [118]:
arr8

array([[0.97643132, 0.37129977],
       [0.48582942, 0.19083978],
       [0.70624454, 0.69207355],
       [0.01576252, 0.00551988],
       [0.0816228 , 0.89158668],
       [0.72745765, 0.29228988]])

In [120]:
arr8[1][1]

0.19083978242970778

In [124]:
arr8[2:5,0]

array([0.70624454, 0.01576252, 0.0816228 ])

In [125]:
arr10=np.random.randint(1,100,(5,5))

In [126]:
arr10

array([[88, 38, 49, 17,  8],
       [48, 15, 95, 93, 65],
       [75, 65, 51, 30, 76],
       [52, 29, 36, 89,  6],
       [ 5, 15, 77, 21, 91]])

In [129]:
arr10[arr10>5]

array([88, 38, 49, 17,  8, 48, 15, 95, 93, 65, 75, 65, 51, 30, 76, 52, 29,
       36, 89,  6, 15, 77, 21, 91])

In [130]:
arr10

array([[88, 38, 49, 17,  8],
       [48, 15, 95, 93, 65],
       [75, 65, 51, 30, 76],
       [52, 29, 36, 89,  6],
       [ 5, 15, 77, 21, 91]])

In [135]:
arr10[1:3,[1,3]]

array([[15, 93],
       [65, 30]])

In [136]:
arr11=np.random.randint(1,3,(3,3))

In [142]:
arr12=np.random.randint(4,8,(3,3))

In [138]:
arr11

array([[1, 2, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [143]:
arr12

array([[5, 5, 4],
       [4, 5, 6],
       [6, 6, 5]])

In [144]:
arr11+arr12

array([[6, 7, 6],
       [6, 7, 8],
       [7, 7, 7]])

In [145]:
arr11*arr12

array([[ 5, 10,  8],
       [ 8, 10, 12],
       [ 6,  6, 10]])

In [146]:
# Matrix Multiplication

arr11@arr12

array([[25, 27, 26],
       [30, 32, 30],
       [21, 22, 20]])

In [147]:
arr11/0

C:\Users\RomulusDome\AppData\Local\Temp\ipykernel_11772\3085431103.py:1: RuntimeWarning: divide by zero encountered in divide
  arr11/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [148]:
arr11**2

array([[1, 4, 4],
       [4, 4, 4],
       [1, 1, 4]])

In [149]:
# Numpy Broadcasting

In [150]:
arr13=np.zeros((4,4))

In [151]:
arr13

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [152]:
row =np.array([1,2,3,4])

In [153]:
row

array([1, 2, 3, 4])

In [154]:
arr13+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [155]:
row.T

array([1, 2, 3, 4])

In [156]:
col=np.array([[1,2,34,3]])

In [157]:
col

array([[ 1,  2, 34,  3]])

In [158]:
col.T

array([[ 1],
       [ 2],
       [34],
       [ 3]])

In [159]:
col.T + arr13

array([[ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [34., 34., 34., 34.],
       [ 3.,  3.,  3.,  3.]])

In [160]:
np.exp(arr13)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [162]:
np.log2(arr13)

C:\Users\RomulusDome\AppData\Local\Temp\ipykernel_11772\3488241091.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr13)


array([[-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])

In [164]:
arr14=np.random.randint(1,3,(3,4))

In [165]:
arr14

array([[2, 1, 1, 1],
       [1, 1, 2, 1],
       [1, 1, 1, 2]])

In [166]:
np.sqrt(arr14)

array([[1.41421356, 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.        , 1.41421356]])

In [167]:
np.exp2(arr14)

array([[4., 2., 2., 2.],
       [2., 2., 4., 2.],
       [2., 2., 2., 4.]])

In [168]:
np.log2(arr14)

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [170]:
np.log(arr14)

array([[0.69314718, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.69314718, 0.        ],
       [0.        , 0.        , 0.        , 0.69314718]])