In [49]:
# NUmpy array Manipulation

In [50]:
import numpy as np 

In [51]:
arr = np.random.randint(1,10,(3,4))

In [52]:
arr

array([[2, 7, 7, 3],
       [9, 1, 3, 7],
       [3, 4, 5, 3]])

In [53]:
arr.reshape(6,2)

array([[2, 7],
       [7, 3],
       [9, 1],
       [3, 7],
       [3, 4],
       [5, 3]])

In [54]:
arr.reshape(2,6)

array([[2, 7, 7, 3, 9, 1],
       [3, 7, 3, 4, 5, 3]])

In [55]:
arr.reshape(4,3)

array([[2, 7, 7],
       [3, 9, 1],
       [3, 7, 3],
       [4, 5, 3]])

In [56]:
arr.reshape(4,-1)

array([[2, 7, 7],
       [3, 9, 1],
       [3, 7, 3],
       [4, 5, 3]])

In [57]:
arr.T

array([[2, 9, 3],
       [7, 1, 4],
       [7, 3, 5],
       [3, 7, 3]])

In [58]:
arr

array([[2, 7, 7, 3],
       [9, 1, 3, 7],
       [3, 4, 5, 3]])

In [59]:
arr.flatten()

array([2, 7, 7, 3, 9, 1, 3, 7, 3, 4, 5, 3])

In [60]:
arr1 = np.array([1,2,3,4,3])

In [61]:
arr1.ndim

1

In [62]:
arr1.T

array([1, 2, 3, 4, 3])

In [63]:
np.expand_dims(arr1,axis =1)

array([[1],
       [2],
       [3],
       [4],
       [3]])

In [64]:
arr1.ndim

1

In [65]:
np.expand_dims(arr1,axis =0)

array([[1, 2, 3, 4, 3]])

In [66]:
arr

array([[2, 7, 7, 3],
       [9, 1, 3, 7],
       [3, 4, 5, 3]])

In [67]:
np.squeeze(arr)

array([[2, 7, 7, 3],
       [9, 1, 3, 7],
       [3, 4, 5, 3]])

In [68]:
data = np.array([[1],[2],[3]])

In [69]:
data

array([[1],
       [2],
       [3]])

In [70]:
np.squeeze(data)

array([1, 2, 3])

In [71]:
arr1

array([1, 2, 3, 4, 3])

In [72]:
np.repeat(arr1,100)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,

In [73]:
np.roll(arr1,2)

array([4, 3, 1, 2, 3])

In [74]:
arr1

array([1, 2, 3, 4, 3])

In [75]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 3]])

In [76]:
# Numpy Binary OPeration

In [77]:
arr2= np.random.randint(1,10,(3,4))

In [78]:
arr3=np.random.randint(1,10,(3,4))

In [79]:
arr2

array([[7, 2, 3, 8],
       [6, 4, 3, 1],
       [9, 2, 8, 8]])

In [80]:
arr3

array([[9, 3, 6, 6],
       [6, 1, 3, 8],
       [9, 3, 7, 1]])

In [81]:
arr2+arr3

array([[16,  5,  9, 14],
       [12,  5,  6,  9],
       [18,  5, 15,  9]])

In [82]:
arr2*arr3

array([[63,  6, 18, 48],
       [36,  4,  9,  8],
       [81,  6, 56,  8]])

In [83]:
arr2-arr3

array([[-2, -1, -3,  2],
       [ 0,  3,  0, -7],
       [ 0, -1,  1,  7]])

In [84]:
arr2/arr3

array([[0.77777778, 0.66666667, 0.5       , 1.33333333],
       [1.        , 4.        , 1.        , 0.125     ],
       [1.        , 0.66666667, 1.14285714, 8.        ]])

In [85]:
arr2%arr3

array([[7, 2, 3, 2],
       [0, 0, 0, 1],
       [0, 2, 1, 0]])

In [86]:
arr2 ** arr3

array([[ 40353607,         8,       729,    262144],
       [    46656,         4,        27,         1],
       [387420489,         8,   2097152,         8]])

In [87]:
arr2& arr3

array([[1, 2, 2, 0],
       [6, 0, 3, 0],
       [9, 2, 0, 0]])

In [88]:
-arr2

array([[-7, -2, -3, -8],
       [-6, -4, -3, -1],
       [-9, -2, -8, -8]])

In [89]:
arr2!=arr3

array([[ True,  True,  True,  True],
       [False,  True, False,  True],
       [False,  True,  True,  True]])

In [90]:
arr2>arr3

array([[False, False, False,  True],
       [False,  True, False, False],
       [False, False,  True,  True]])

In [91]:
# Numpy String Functions

In [92]:
arr4= np.array(['sanjeev','jamatia'])

In [94]:
np.char.upper(arr4)

array(['SANJEEV', 'JAMATIA'], dtype='<U7')

In [95]:
np.char.title(arr4)

array(['Sanjeev', 'Jamatia'], dtype='<U7')

In [97]:
np.char.capitalize(arr4)

array(['Sanjeev', 'Jamatia'], dtype='<U7')

In [98]:
#Numpy Mathematical function

In [100]:
arr

array([[2, 7, 7, 3],
       [9, 1, 3, 7],
       [3, 4, 5, 3]])

In [101]:
np.sinc(arr)

array([[-3.89817183e-17,  3.89817183e-17,  3.89817183e-17,
         3.89817183e-17],
       [ 3.89817183e-17,  3.89817183e-17,  3.89817183e-17,
         3.89817183e-17],
       [ 3.89817183e-17, -3.89817183e-17,  3.89817183e-17,
         3.89817183e-17]])

In [102]:
np.tanh(arr2+arr3)

array([[1.        , 0.9999092 , 0.99999997, 1.        ],
       [1.        , 0.9999092 , 0.99998771, 0.99999997],
       [1.        , 0.9999092 , 1.        , 0.99999997]])

In [103]:
np.cos(arr3+1)

array([[-0.83907153, -0.65364362,  0.75390225,  0.75390225],
       [ 0.75390225, -0.41614684, -0.65364362, -0.91113026],
       [-0.83907153, -0.65364362, -0.14550003, -0.41614684]])

In [104]:
np.log10(arr3)

array([[0.95424251, 0.47712125, 0.77815125, 0.77815125],
       [0.77815125, 0.        , 0.47712125, 0.90308999],
       [0.95424251, 0.47712125, 0.84509804, 0.        ]])

In [105]:
np.exp(arr3)

array([[8.10308393e+03, 2.00855369e+01, 4.03428793e+02, 4.03428793e+02],
       [4.03428793e+02, 2.71828183e+00, 2.00855369e+01, 2.98095799e+03],
       [8.10308393e+03, 2.00855369e+01, 1.09663316e+03, 2.71828183e+00]])

In [106]:
np.sqrt(arr3)

array([[3.        , 1.73205081, 2.44948974, 2.44948974],
       [2.44948974, 1.        , 1.73205081, 2.82842712],
       [3.        , 1.73205081, 2.64575131, 1.        ]])

In [108]:
np.power(arr3,2)

array([[81,  9, 36, 36],
       [36,  1,  9, 64],
       [81,  9, 49,  1]], dtype=int32)

In [110]:
np.median(arr3)

6.0

In [111]:
np.std(arr3)

2.7638539919628333

In [112]:
np.mean(arr3)

5.166666666666667

In [113]:
np.var(arr3)

7.638888888888889

In [114]:
np.min(arr3)

1

In [115]:
np.max(arr3)

9