In [1]:
import numpy as np 

In [2]:
arr=np.array([3,1,4,5,2,5,2,3,54,54,673,2,4,5,7,6,4])

In [3]:
arr

array([  3,   1,   4,   5,   2,   5,   2,   3,  54,  54, 673,   2,   4,
         5,   7,   6,   4])

In [4]:
np.sort(arr)

array([  1,   2,   2,   2,   3,   3,   4,   4,   4,   5,   5,   5,   6,
         7,  54,  54, 673])

In [6]:
np.searchsorted(arr,444)

17

In [7]:
arr1=np.array([0,1,2,3,40,33,4,0])

In [8]:
np.count_nonzero(arr1)

6

In [9]:
arr

array([  3,   1,   4,   5,   2,   5,   2,   3,  54,  54, 673,   2,   4,
         5,   7,   6,   4])

In [10]:
np.where(arr > 6)

(array([ 8,  9, 10, 14], dtype=int64),)

In [12]:
np.extract(arr>6,arr)

array([ 54,  54, 673,   7])

In [13]:
arr.byteswap()

array([   50331648,    16777216,    67108864,    83886080,    33554432,
          83886080,    33554432,    50331648,   905969664,   905969664,
       -1593704448,    33554432,    67108864,    83886080,   117440512,
         100663296,    67108864])

In [14]:
a=np.copy(arr)

In [15]:
a

array([  3,   1,   4,   5,   2,   5,   2,   3,  54,  54, 673,   2,   4,
         5,   7,   6,   4])

In [16]:
b=arr.view()

In [17]:
b

array([  3,   1,   4,   5,   2,   5,   2,   3,  54,  54, 673,   2,   4,
         5,   7,   6,   4])

In [18]:
b[0]=67

In [19]:
b

array([ 67,   1,   4,   5,   2,   5,   2,   3,  54,  54, 673,   2,   4,
         5,   7,   6,   4])

In [20]:
# NUMPY matrix library

In [21]:
import numpy.matlib as nm

In [22]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [23]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# numoy linear algebra

In [26]:
arr2= np.random.randint([[2,3],[4,5]])

In [27]:
arr3=np.random.randint([[4,5],[7,9]])

In [28]:
np.dot(arr2,arr3)

array([[3, 0],
       [0, 0]])

In [29]:
arr2@arr3

array([[3, 0],
       [0, 0]])